### ISSUE TITLE
Download Image

### ISSUE THREAD

**Issue by ABHISHEK-AMRUTE** [ABHISHEK-AMRUTE/WallpaperApp#1]
In the second page named **preview_image.dart**, add functionalities to download the current image.
Use camel casing for the variable name. Write neet code.
Happy Coding

**Comment by hadi-codes** [comment]
i could do that

**Comment by ABHISHEK-AMRUTE** [comment]
Fine, I am assigning it to you, make sure you follow the conventions.
If you find this repo helpful for your Hacktoberfest journey then please drop a star.

**Comment by ABHISHEK-AMRUTE** [comment]
Issue solved by @bigblackclock Hadi
